day_start_weekday: "04:00"
day_start_weekend: "07:00"

energy_levels_weekday: 
  "04:00" : low
  "07:00" : medium
  "08:00" : high
  "13:00" : low
  "14:00" : medium
  "16:00" : high
  "19:00" : low

energy_levels_weekend:
  "07:00" : medium
  "08:00" : high
  "13:00" : low
  "14:00" : medium
  "16:00" : high
  "19:00" : low
